# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /nethome/ahimanshu3/DSP_Project/PROJECT_WORKING/Vga_projrct/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /nethome/ahimanshu3/DSP_Project/PROJECT_WORKING/Vga_projrct/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /nethome/ahimanshu3/DSP_Project/PROJECT_WORKING/Vga_projrct/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /nethome/ahimanshu3/DSP_Project/PROJECT_WORKING/Vga_projrct/project_1/project_1.srcs/sources_1/new/RAM_dual.vhd
  /nethome/ahimanshu3/DSP_Project/PROJECT_WORKING/Vga_projrct/project_1/project_1.srcs/sources_1/imports/src/absolute_sum.vhd
  /nethome/ahimanshu3/DSP_Project/PROJECT_WORKING/Vga_projrct/project_1/project_1.srcs/sources_1/imports/src/comp_bin.vhd
  /nethome/ahimanshu3/DSP_Project/PROJECT_WORKING/Vga_projrct/project_1/project_1.srcs/sources_1/imports/src/edge_detector.vhd
  {/nethome/ahimanshu3/DSP_Project/PROJECT_WORKING/Vga_projrct/project_1/project_1.srcs/sources_1/imports/New folder/myreceiver.vhd}
  /nethome/ahimanshu3/DSP_Project/PROJECT_WORKING/Vga_projrct/project_1/project_1.srcs/sources_1/imports/src/row_shifter.vhd
  /nethome/ahimanshu3/DSP_Project/PROJECT_WORKING/Vga_projrct/project_1/project_1.srcs/sources_1/imports/src/sobel_filter.vhd
  /nethome/ahimanshu3/DSP_Project/PROJECT_WORKING/Vga_projrct/project_1/project_1.srcs/sources_1/imports/Vga/top_vga.vhd
  /nethome/ahimanshu3/DSP_Project/PROJECT_WORKING/Vga_projrct/project_1/project_1.srcs/sources_1/imports/Vga/vga_controller.vhd
  /nethome/ahimanshu3/DSP_Project/PROJECT_WORKING/Vga_projrct/project_1/project_1.srcs/sources_1/imports/Vga/vga_test.vhd
  /nethome/ahimanshu3/DSP_Project/PROJECT_WORKING/Vga_projrct/project_1/project_1.srcs/sources_1/new/Our_design.vhd
}
add_files /nethome/ahimanshu3/DSP_Project/PROJECT_WORKING/Vga_projrct/project_1/project_1.srcs/sources_1/bd/clk_25/clk_25.bd
set_property used_in_implementation false [get_files -all /nethome/ahimanshu3/DSP_Project/PROJECT_WORKING/Vga_projrct/project_1/project_1.srcs/sources_1/bd/clk_25/ip/clk_25_clk_wiz_0_0/clk_25_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /nethome/ahimanshu3/DSP_Project/PROJECT_WORKING/Vga_projrct/project_1/project_1.srcs/sources_1/bd/clk_25/ip/clk_25_clk_wiz_0_0/clk_25_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /nethome/ahimanshu3/DSP_Project/PROJECT_WORKING/Vga_projrct/project_1/project_1.srcs/sources_1/bd/clk_25/ip/clk_25_clk_wiz_0_0/clk_25_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /nethome/ahimanshu3/DSP_Project/PROJECT_WORKING/Vga_projrct/project_1/project_1.srcs/sources_1/bd/clk_25/clk_25_ooc.xdc]
set_property is_locked true [get_files /nethome/ahimanshu3/DSP_Project/PROJECT_WORKING/Vga_projrct/project_1/project_1.srcs/sources_1/bd/clk_25/clk_25.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /nethome/ahimanshu3/DSP_Project/PROJECT_WORKING/Vga_projrct/project_1/project_1.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files /nethome/ahimanshu3/DSP_Project/PROJECT_WORKING/Vga_projrct/project_1/project_1.srcs/constrs_1/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Our_design -part xc7a35tcpg236-1 -directive AlternateRoutability -resource_sharing off -no_lc -shreg_min_size 10


write_checkpoint -force -noxdef Our_design.dcp

catch { report_utilization -file Our_design_utilization_synth.rpt -pb Our_design_utilization_synth.pb }
