# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/block_rom/block_rom.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_rom || ORIG_REF_NAME==block_rom}]

# IP: bd/block_rom/ip/block_rom_blk_mem_gen_0_0/block_rom_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_rom_blk_mem_gen_0_0 || ORIG_REF_NAME==block_rom_blk_mem_gen_0_0}]

# XDC: bd/block_rom/block_rom_ooc.xdc
